//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/_Scripts/Input/InputAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputPlayerSystem: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputPlayerSystem()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputAction"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""644f54c1-0d90-423f-bb91-2a01e9113eb4"",
            ""actions"": [
                {
                    ""name"": ""HardDropeFigure"",
                    ""type"": ""Button"",
                    ""id"": ""b7f2d690-fd08-4c06-bfe4-fdb45bbe70fe"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwapFigure"",
                    ""type"": ""Button"",
                    ""id"": ""dfe7e36f-3815-4c66-bc47-b3a451254332"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RotateFigure"",
                    ""type"": ""Button"",
                    ""id"": ""a36485ed-40b9-40ea-9ce2-d48807f91845"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SlowDropeFigure"",
                    ""type"": ""Button"",
                    ""id"": ""dc4a2590-8bb6-4508-9b8f-5cc953fe1de7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveRight"",
                    ""type"": ""Button"",
                    ""id"": ""6a282256-7d4a-45f7-b248-4cc10a303b53"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveLeft"",
                    ""type"": ""Button"",
                    ""id"": ""5c22eb2f-5827-407e-a561-c3032e925527"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a8b6399f-1b2d-463c-b94c-09ff248ab178"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HardDropeFigure"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bde4d7a2-e72b-43da-b778-ae1f5827fb43"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwapFigure"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""42ec74f4-98cc-4e91-a7ff-0500312047a8"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateFigure"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""713cf41c-11b7-40ce-8827-4cf876bcc7cf"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateFigure"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f9007345-ff87-4fce-9ce3-f45e11f35e6e"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlowDropeFigure"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""06526824-327c-4947-af50-32e12b348779"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1c31ddf-d6a3-4ab4-8494-2c8a5cf11079"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_HardDropeFigure = m_Player.FindAction("HardDropeFigure", throwIfNotFound: true);
        m_Player_SwapFigure = m_Player.FindAction("SwapFigure", throwIfNotFound: true);
        m_Player_RotateFigure = m_Player.FindAction("RotateFigure", throwIfNotFound: true);
        m_Player_SlowDropeFigure = m_Player.FindAction("SlowDropeFigure", throwIfNotFound: true);
        m_Player_MoveRight = m_Player.FindAction("MoveRight", throwIfNotFound: true);
        m_Player_MoveLeft = m_Player.FindAction("MoveLeft", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_HardDropeFigure;
    private readonly InputAction m_Player_SwapFigure;
    private readonly InputAction m_Player_RotateFigure;
    private readonly InputAction m_Player_SlowDropeFigure;
    private readonly InputAction m_Player_MoveRight;
    private readonly InputAction m_Player_MoveLeft;
    public struct PlayerActions
    {
        private @InputPlayerSystem m_Wrapper;
        public PlayerActions(@InputPlayerSystem wrapper) { m_Wrapper = wrapper; }
        public InputAction @HardDropeFigure => m_Wrapper.m_Player_HardDropeFigure;
        public InputAction @SwapFigure => m_Wrapper.m_Player_SwapFigure;
        public InputAction @RotateFigure => m_Wrapper.m_Player_RotateFigure;
        public InputAction @SlowDropeFigure => m_Wrapper.m_Player_SlowDropeFigure;
        public InputAction @MoveRight => m_Wrapper.m_Player_MoveRight;
        public InputAction @MoveLeft => m_Wrapper.m_Player_MoveLeft;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @HardDropeFigure.started += instance.OnHardDropeFigure;
            @HardDropeFigure.performed += instance.OnHardDropeFigure;
            @HardDropeFigure.canceled += instance.OnHardDropeFigure;
            @SwapFigure.started += instance.OnSwapFigure;
            @SwapFigure.performed += instance.OnSwapFigure;
            @SwapFigure.canceled += instance.OnSwapFigure;
            @RotateFigure.started += instance.OnRotateFigure;
            @RotateFigure.performed += instance.OnRotateFigure;
            @RotateFigure.canceled += instance.OnRotateFigure;
            @SlowDropeFigure.started += instance.OnSlowDropeFigure;
            @SlowDropeFigure.performed += instance.OnSlowDropeFigure;
            @SlowDropeFigure.canceled += instance.OnSlowDropeFigure;
            @MoveRight.started += instance.OnMoveRight;
            @MoveRight.performed += instance.OnMoveRight;
            @MoveRight.canceled += instance.OnMoveRight;
            @MoveLeft.started += instance.OnMoveLeft;
            @MoveLeft.performed += instance.OnMoveLeft;
            @MoveLeft.canceled += instance.OnMoveLeft;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @HardDropeFigure.started -= instance.OnHardDropeFigure;
            @HardDropeFigure.performed -= instance.OnHardDropeFigure;
            @HardDropeFigure.canceled -= instance.OnHardDropeFigure;
            @SwapFigure.started -= instance.OnSwapFigure;
            @SwapFigure.performed -= instance.OnSwapFigure;
            @SwapFigure.canceled -= instance.OnSwapFigure;
            @RotateFigure.started -= instance.OnRotateFigure;
            @RotateFigure.performed -= instance.OnRotateFigure;
            @RotateFigure.canceled -= instance.OnRotateFigure;
            @SlowDropeFigure.started -= instance.OnSlowDropeFigure;
            @SlowDropeFigure.performed -= instance.OnSlowDropeFigure;
            @SlowDropeFigure.canceled -= instance.OnSlowDropeFigure;
            @MoveRight.started -= instance.OnMoveRight;
            @MoveRight.performed -= instance.OnMoveRight;
            @MoveRight.canceled -= instance.OnMoveRight;
            @MoveLeft.started -= instance.OnMoveLeft;
            @MoveLeft.performed -= instance.OnMoveLeft;
            @MoveLeft.canceled -= instance.OnMoveLeft;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnHardDropeFigure(InputAction.CallbackContext context);
        void OnSwapFigure(InputAction.CallbackContext context);
        void OnRotateFigure(InputAction.CallbackContext context);
        void OnSlowDropeFigure(InputAction.CallbackContext context);
        void OnMoveRight(InputAction.CallbackContext context);
        void OnMoveLeft(InputAction.CallbackContext context);
    }
}
